target 'CFOnlineShop' do
platform:ios,'9.0'

pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDCycleScrollView','~> 1.75'
pod 'RollingNotice'
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage', '~> 4.3.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'Masonry', '~> 1.1.0'

end
